### ISSUE TITLE
Rewrite integration for LegacyFactions

### ISSUE THREAD

**Issue by 28andrew** [xXAndrew28Xx/Conquer#6]
I just rewrote Conquer, so the old API is no longer valid. @markhughes, I was wondering if you would like to rewrite your own implementation and keep it in your plugin, LegacyFactions, or for me to write the plugin and keep the implementation in this repository. I'm fine with either option.

**Comment by 28andrew** [comment]
I made a [wiki page](https://github.com/xXAndrew28Xx/Conquer/wiki/Writing-your-own-implementation) on how to write an implementation too.

**Comment by 28andrew** [comment]
One last option is that I can PR an implementation into the `LegacyFactions` repository, trying the best I can to adhere to its code style. If I don't get a reply within a week, I'll just write the implementation inside this repository but I'll still be open to change where the implementation is.

**Comment by markhughes** [comment]
Hey, I'm not actively working on LegacyFactions right now. But I can probably fix it up in a few months.

**Comment by abandonedaccount6235** [comment]
Thanks, Mark. Looking forward to your PR.

**Comment by 28andrew** [comment]
For now, I think I'm just going to write temporary integration inside Conquer.

**Comment by 28andrew** [comment]
Written support
https://github.com/xXAndrew28Xx/Conquer/tree/master/legacyfactions-impl
